### ISSUE TITLE
Hybrid: Elimination ordering requires DCFactor key

### ISSUE THREAD

**Issue by varunagrawal** [varunagrawal/gtsam#27]
~~This may be intended, but an issue I ran into this weekend is that if the ordering has the first key as a key which is not a part of a DCFactor, then due to no pre-existing `DecisionTree`, the sum operator causes a runtime exception.~~

~~It took me over a day to figure this out but I managed to fix it by enforcing DCFactor keys to be inserted first in the ordering. Again, I don't know if this intentional but it seems that it shouldn't be since it limits our elimination ordering possibilities.~~

Elimination craps out when the ordering has a variable which is not part of a DCFactor. This is because the `apply(Unary op)` method of the DecisionTree to be created doesn't know what to do when a root node doesn't already exist.

**Comment by dellaert** [comment]
You should be able to give any ordering which has continuous keys first, hence you should fix the elimination code.

**Comment by varunagrawal** [comment]
Yup worked on this and I believe the issue is different from what I have reported.

Seems like if we eliminate any continuous variable that is not connected to a DCFactor then we will encounter a runtime exception. This seems to be due to the fact that `root_` is not initialized in the default constructor of `DecisionTree`. Of course this needs to be backed up by a test. 🙂

**Comment by varunagrawal** [comment]
Holy mother of God I finally fixed this. Not a fun way to spend my weekend. 😢
